# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fdtd_python',
                'doc_host': 'https://gbeane66.github.io',
                'git_url': 'https://github.com/gbeane66/fdtd_python',
                'lib_path': 'fdtd_python'},
  'syms': {'fdtd_python.core': {'fdtd_python.core.foo': ('core.html#foo', 'fdtd_python/core.py')}}}
